services:
    webserver:
        restart: on-failure
        env_file:
          - .env
        image: "webserver:${VERSION}"
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
            - "80:80"